path: mushroom-data
train: mushroom-data/train
test: mushroom-data/test
val: mushroom-data/valid

# Classes
nc: 14 # replace based on your dataset's number of classes

# Class names
names:
  0: Amanita citrina
  1: Amanita hemibapha
  2: Amanita javanica
  3: Amanita pantherina
  4: Amanita princeps
  5: Boletus reticulatus
  6: Coltricia perennis
  7: Gyromitra infula
  8: Hygrophoropsis aurantiaca
  9: Imleria badia
  10: Lactarius turpis
  11: Russula emetica
  12: Suillus grevillei
  13: Suillus luteus

#data augmentations 
#color/light augmentations first
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
